function(source_groups_from_paths root_path)
    foreach(file IN ITEMS ${ARGN})
        if (IS_ABSOLUTE "${file}")
            file(RELATIVE_PATH file_relative "${root_path}" "${file}")
        else()
            set(file_relative "${file}")
        endif()
        get_filename_component(file_path "${file_relative}" PATH)
        string(REPLACE "/" "\\" file_path "${file_path}")
        source_group("${file_path}" FILES "${file}")
    endforeach()
endfunction(source_groups_from_paths)